### ISSUE TITLE
Upgrade to 0.2.6 failed on redmine 3.2.0

### ISSUE THREAD

**Issue by ppoektos** [paginagmbh/redmine_lightbox2#27]
```
git clone https://github.com/paginagmbh/redmine_lightbox2
cd redmine_lightbox2/
git branch -a
git checkout redmine-3.0-3.2
cd ..
rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
ArgumentError: :version_or_higher accepts a version string only
/var/www/rm320/lib/redmine/plugin.rb:208:in `block in requires_redmine'
/var/www/rm320/lib/redmine/plugin.rb:205:in `each'
/var/www/rm320/lib/redmine/plugin.rb:205:in `requires_redmine'
/var/www/rm320/plugins/redmine_lightbox2/init.rb:12:in `block in <top (required)>'
/var/www/rm320/lib/redmine/plugin.rb:75:in `instance_eval'
/var/www/rm320/lib/redmine/plugin.rb:75:in `register'
/var/www/rm320/plugins/redmine_lightbox2/init.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/var/www/rm320/lib/redmine/plugin.rb:155:in `block in load'
/var/www/rm320/lib/redmine/plugin.rb:146:in `each'
/var/www/rm320/lib/redmine/plugin.rb:146:in `load'
/var/www/rm320/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/var/www/rm320/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by tofi86** [comment]
Oh gosh, so sorry! Only edited the required version string but missed to change the method from `:version_or_higher` to `:version:`

New version v0.2.7 was released just now on branch `redmine-3.0-3.2`
Sorry!

**Comment by ppoektos** [comment]
Thanks for fast support! It works now.

**Comment by tofi86** [comment]
Perfect, glad it works...
