### ISSUE TITLE
Redmine 5.0.0 Plugins Rake Migrate fails.

### ISSUE THREAD

**Issue by aminoacidity** [paginagmbh/redmine_lightbox2#88]
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- patches/attachments_patch
/var/lib/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/usr/share/redmine/plugins/redmine_lightbox2/init.rb:3:in `<top (required)>'
/usr/share/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/usr/share/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr/share/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/usr/share/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
/usr/share/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by cypx** [comment]
Same here, using this fork https://github.com/AlphaNodes/redmine_lightbox solve problem for me

**Comment by eximius313** [comment]
Are there any plans to support 5.x here?

**Comment by zlcolin** [comment]
+1
